### ISSUE TITLE
Sorting in more than one column with different sort options

### ISSUE THREAD

**Issue by niden** [khallmark/LBHToolkit-Library#1]
Greetings

It would be great if we can sort on different columns and with a different order for each.

For instance say I want to sort for lastname ASC and firstname DESC. I could do something like this:

``` php
       $tablemaker = $this->_helper->tableMaker(
            array(
                'table_name'    => 'my_members',
                'class'         => 'list',
                'default_sort'  => 'u.lastname, u.firstname DESC',
                'count'         => 10,
                'adapter'       => new LBHToolkit_TableMaker_Adapter_Doctrine()
            )

The above example is for the Doctrine adapter. 

Thanks!
```

**Comment by khallmark** [comment]
Sorry for the delay in getting this fixed. I've been wracking my brain for the best solution. I finally figured it out. 

I'm going to change "default_sort" and all the other "sort" attributes to accept callbacks of the form:

```
function (&$data, $pagingInfo) {
    // insert logic here
}
```

$data will be the data passed to the tablemaker, whatever it is (Doctrine_Query, Zend_Db_Query, array, etc...) 
$pagingInfo will be the current LBHToolkit_TableMaker_Paging data object

The callback for "default_sort" will let you set whatever custom sorting you require. This way, you can write system specific sorting rules.

The callback for "sort" attributes will let you perform custom logic for sorting on that column. This will give you unparalleled flexibility in sorting each column.

The sorting in the url will be captured as:

/sort/$column_id/order/{asc|desc}

This solution will greatly improve application security as well.

Existing formats for passing sort information will continue to be supported. 

This should allow you to customize the sorting to your hearts content. Hopefully I can implement this sometime tomorrow afternoon.
